name: build manylinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build in manylinux container
      run: docker run --rm -v $DIR:/repo --rm safijari/manylinux2010-x64 /repo/build.sh
